<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.6                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2015                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2015
 *
 * Generated from xml/schema/CRM/Timetrack/Punch.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
class CRM_Timetrack_DAO_Punch extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   */
  static $_tableName = 'kpunch';
  /**
   * static instance to hold the field values
   *
   * @var array
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Punch Id
   *
   * @var int unsigned
   */
  public $id;
  /**
   * Author of the punch.
   *
   * @var int unsigned
   */
  public $contact_id;
  /**
   * Task associated to the punch (FK to ktask).
   *
   * @var int unsigned
   */
  public $ktask_id;
  /**
   * Start timestamp of the punch.
   *
   * @var int unsigned
   */
  public $begin;
  /**
   * Duration (in seconds) of the punch.
   *
   * @var int unsigned
   */
  public $duration;
  /**
   * Punch comment, provides more information on what was done.
   *
   * @var string
   */
  public $comment;
  /**
   * FIXME: probably never used. Intended to distinguish volunteer/paid internally?
   *
   * @var int unsigned
   */
  public $billable_intern;
  /**
   * FIXME: probably never used. Whether to bill the client for this or not.
   *
   * @var int unsigned
   */
  public $billable_client;
  /**
   * FIXME: probably never used. Rate at which to invoice.
   *
   * @var float
   */
  public $rate;
  /**
   * Invoice/order reference.
   *
   * @var int unsigned
   */
  public $order_reference;
  /**
   * class constructor
   *
   * @return kpunch
   */
  function __construct()
  {
    $this->__table = 'kpunch';
    parent::__construct();
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
        'timetrack_punch_id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Timetrack Punch ID') ,
          'description' => 'Punch Id',
          'required' => true,
        ) ,
        'contact_idd' => array(
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Contact ID') ,
          'description' => 'Author of the punch.',
          'required' => true,
        ) ,
        'ktask_id' => array(
          'name' => 'ktask_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Task associated to the punch (FK to ktask).',
          'required' => true,
        ) ,
        'begin' => array(
          'name' => 'begin',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Begin') ,
          'description' => 'Start timestamp of the punch.',
          'required' => true,
        ) ,
        'duration' => array(
          'name' => 'duration',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Duration') ,
          'description' => 'Duration (in seconds) of the punch.',
          'required' => false,
        ) ,
        'comment' => array(
          'name' => 'comment',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Comment') ,
          'description' => 'Punch comment, provides more information on what was done.',
          'required' => false,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'billable_intern' => array(
          'name' => 'billable_intern',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Billable Intern') ,
          'description' => 'FIXME: probably never used. Intended to distinguish volunteer/paid internally?',
          'required' => true,
          'default' => '1',
        ) ,
        'billable_client' => array(
          'name' => 'billable_client',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Billable Client') ,
          'description' => 'FIXME: probably never used. Whether to bill the client for this or not.',
          'required' => true,
          'default' => '1',
        ) ,
        'rate' => array(
          'name' => 'rate',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => ts('Rate') ,
          'description' => 'FIXME: probably never used. Rate at which to invoice.',
          'precision' => array(
            20,
            2
          ) ,
        ) ,
        'order_reference' => array(
          'name' => 'order_reference',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Order Reference') ,
          'description' => 'Invoice/order reference.',
        ) ,
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'timetrack_punch_id',
        'contact_id' => 'contact_id',
        'ktask_id' => 'ktask_id',
        'begin' => 'begin',
        'duration' => 'duration',
        'comment' => 'comment',
        'billable_intern' => 'billable_intern',
        'billable_client' => 'billable_client',
        'rate' => 'rate',
        'order_reference' => 'order_reference',
      );
    }
    return self::$_fieldKeys;
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import[''] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export[''] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}
