<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from coop.symbiotic.timetrack/xml/schema/CRM/Timetrack/Timetracktask.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:449c12b36ebdadd4e674cbf72157bd96)
 */
use CRM_Timetrack_ExtensionUtil as E;

/**
 * Database access object for the Timetracktask entity.
 */
class CRM_Timetrack_DAO_Timetracktask extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_timetracktask';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Timetracktask ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Case
   *
   * @var int
   */
  public $case_id;

  /**
   * Task Title
   *
   * @var string
   */
  public $title;

  /**
   * Task Description
   *
   * @var text
   */
  public $description;

  /**
   * Task status
   *
   * @var int
   */
  public $state;

  /**
   * Task estimate in hours
   *
   * @var int
   */
  public $estimate;

  /**
   * Expected task start date
   *
   * @var timestamp
   */
  public $begin;

  /**
   * Expected task end date
   *
   * @var timestamp
   */
  public $end;

  /**
   * Task Lead, FK to Contact
   *
   * @var int
   */
  public $lead;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_timetracktask';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Timetracktasks') : E::ts('Timetracktask');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'case_id', 'civicrm_case', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'lead', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Timetracktask ID'),
          'required' => TRUE,
          'where' => 'civicrm_timetracktask.id',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => '1.0',
        ],
        'case_id' => [
          'name' => 'case_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Case'),
          'where' => 'civicrm_timetracktask.case_id',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'FKClassName' => 'CRM_Case_DAO_Case',
          'add' => '1.0',
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Title'),
          'description' => E::ts('Task Title'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_timetracktask.title',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Description'),
          'description' => E::ts('Task Description'),
          'where' => 'civicrm_timetracktask.description',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'state' => [
          'name' => 'state',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('State'),
          'description' => E::ts('Task status'),
          'where' => 'civicrm_timetracktask.state',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'estimate' => [
          'name' => 'estimate',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Estimate'),
          'description' => E::ts('Task estimate in hours'),
          'where' => 'civicrm_timetracktask.estimate',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'begin' => [
          'name' => 'begin',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Start Date'),
          'description' => E::ts('Expected task start date'),
          'where' => 'civicrm_timetracktask.begin',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'end' => [
          'name' => 'end',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('End Date'),
          'description' => E::ts('Expected task end date'),
          'where' => 'civicrm_timetracktask.end',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'lead' => [
          'name' => 'lead',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Lead'),
          'description' => E::ts('Task Lead, FK to Contact'),
          'where' => 'civicrm_timetracktask.lead',
          'table_name' => 'civicrm_timetracktask',
          'entity' => 'Timetracktask',
          'bao' => 'CRM_Timetrack_DAO_Timetracktask',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => '1.0',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'timetracktask', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'timetracktask', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
