-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_timetracktask`;
DROP TABLE IF EXISTS `kpunch`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_timetracktask
-- *
-- * Timetrack Task
-- *
-- *******************************************************/
CREATE TABLE `civicrm_timetracktask` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Timetracktask ID',
  `case_id` int unsigned COMMENT 'FK to Case',
  `title` varchar(255) COMMENT 'Task Title',
  `description` text COMMENT 'Task Description',
  `state` int unsigned COMMENT 'Task status',
  `estimate` int unsigned COMMENT 'Task estimate in hours',
  `begin` timestamp COMMENT 'Expected task start date',
  `end` timestamp COMMENT 'Expected task end date',
  `lead` int unsigned COMMENT 'Task Lead, FK to Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_timetracktask_case_id FOREIGN KEY (`case_id`) REFERENCES `civicrm_case`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_timetracktask_lead FOREIGN KEY (`lead`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * kpunch
-- *
-- * Timetrack Punch
-- *
-- *******************************************************/
CREATE TABLE `kpunch` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Timetrackpunch ID',
  `contact_id` int unsigned NOT NULL COMMENT 'Author of the punch.',
  `ktask_id` int unsigned NOT NULL COMMENT 'Task associated to the punch (FK to ktask).',
  `begin` datetime NOT NULL COMMENT 'Start date of the punch.',
  `duration` int unsigned NULL COMMENT 'Duration (in seconds) of the punch.',
  `comment` varchar(255) NULL COMMENT 'Punch comment, provides more information on what was done.',
  `billable_intern` int unsigned NOT NULL DEFAULT 1 COMMENT 'FIXME: probably never used. Intended to distinguish volunteer/paid internally?',
  `billable_client` int unsigned NOT NULL DEFAULT 1 COMMENT 'FIXME: probably never used. Whether to bill the client for this or not.',
  `rate` decimal(20,2) COMMENT 'FIXME: probably never used. Rate at which to invoice.',
  `order_reference` int unsigned COMMENT 'Invoice/order reference.',
  PRIMARY KEY (`id`),
  KEY `contact_id` (`contact_id`),
  KEY `order_reference` (`order_reference`),
  KEY `FK_kpunch_korder_line_id` (`korder_line_id`),
  KEY `FK_kpunch_korder_id` (`korder_id`),
  KEY `ktask_id` (`ktask_id`),
  CONSTRAINT `FK_kpunch_contact_id` FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_kpunch_korder_id` FOREIGN KEY (`korder_id`) REFERENCES `korder` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_kpunch_korder_line_id` FOREIGN KEY (`korder_line_id`) REFERENCES `korder_line` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_kpunch_line_id` FOREIGN KEY (`korder_line_id`) REFERENCES `civicrm_line_item` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_ktask_id` FOREIGN KEY (`ktask_id`) REFERENCES `civicrm_timetracktask` (`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;
