-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
-- 

-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_timetracktask`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_timetracktask
-- *
-- * Timetrack Task
-- *
-- *******************************************************/
--
CREATE TABLE `civicrm_timetracktask` (
  `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique Timetracktask ID',
  `case_id` int unsigned    COMMENT 'FK to Case',
  `title` varchar(255)    COMMENT 'Task Title',
  `description` text    COMMENT 'Task Description',
  `state` int unsigned    COMMENT 'Task status',
  `estimate` int unsigned    COMMENT 'Task estimate in hours',
  `begin` timestamp    COMMENT 'Expected task start date',
  `end` timestamp    COMMENT 'Expected task end date',
  `lead` int unsigned    COMMENT 'Task Lead, FK to Contact',
   PRIMARY KEY (`id`),
   CONSTRAINT FK_civicrm_timetracktask_case_id FOREIGN KEY (`case_id`) REFERENCES `civicrm_case`(`id`) ON DELETE SET NULL,          CONSTRAINT FK_civicrm_timetracktask_lead FOREIGN KEY (`lead`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;
